version: "3.4"

services:
 webapi:
    container_name: schoolscalendar
    image: schoolscalendar/net6
    environment:
    - PORT=8000
    ports:
    - 8000:8000
    build:
      context: .
      dockerfile: Dockerfile